package Enums;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public enum Currency {

  EUR("Euro", "€", "EUR", "Akrotiri and Dhekelia", "Andorra", "Austria", "Belgium", "Cyprus", "Estonia", "Finland", "France", "Germany", "Greece", "Ireland", "Italy", "Kosovo", "Latvia", "Lithuania", "Luxembourg", "Malta", "Monaco", "Montenegro", "Netherlands", "Portugal", "San Marino", "Slovakia", "Slovenia", "Spain", " Vatican City", "Zimbabwe"),
  LRD("Liberian dollar", "$", "LRD", "Liberia"),
  KES("Kenyan shilling", "Sh", "KES", "Kenya"),
  AWG("Aruban florin", "ƒ", "AWG", "Aruba"),
  COP("Colombian peso", "$", "COP", "Colombia"),
  GNF("Guinean franc", "Fr", "GNF", "Guinea"),
  NPR("Nepalese rupee", "₨", "NPR", "Nepal"),
  PKR("Pakistani rupee", "₨", "PKR", "Pakistan"),
  SLL("Sierra Leonean leone", "Le", "SLL", "Sierra Leone"),
  QAR("Qatari riyal", "ر.ق", "QAR", "Qatar"),
  SDG("Sudanese pound", "ج.س.", "SDG", "Sudan"),
  PRB("Transnistrian ruble", "р.", "PRB", "Transnistria"),
  UAH("Ukrainian hryvnia", "₴", "UAH", "Ukraine"),
  JOD("Jordanian dinar", "د.ا", "JOD", "Jordan", "Palestine"),
  BOB("Bolivian boliviano", "Bs.", "BOB", "Bolivia"),
  AOA("Angolan kwanza", "Kz", "AOA", "Angola"),
  KYD("Cayman Islands dollar", "$", "KYD", "Cayman Islands"),
  ERN("Eritrean nakfa", "Nfk", "ERN", "Eritrea"),
  VEF("Venezuelan bolívar", "Bs", "VEF", "Venezuela"),
  DOP("Dominican peso", "$", "DOP", "Dominican Republic"),
  SZL("Swazi lilangeni", "L", "SZL", "Swaziland"),
  SSP("South Sudanese pound", "£", "SSP", "South Sudan"),
  KGS("Kyrgyzstani som", "с", "KGS", "Kyrgyzstan"),
  XPF("CFP franc", "Fr", "XPF", "French Polynesia", "New Caledonia", "Wallis and Futuna"),
  JMD("Jamaican dollar", "$", "JMD", "Jamaica"),
  VUV("Vanuatu vatu", "Vt", "VUV", "Vanuatu"),
  BTN("Bhutanese ngultrum", "Nu.", "BTN", "Bhutan"),
  AFN("Afghan afghani", "؋", "AFN", "Afghanistan"),
  CRC("Costa Rican colón", "₡", "CRC", "Costa Rica"),
  RSD("Serbian dinar", "дин. or din.", "RSD", "Serbia"),
  ZAR("South African rand", "R", "ZAR", "Lesotho", "Namibia", "South Africa"),
  PAB("Panamanian balboa", "B/.", "PAB", "Panama"),
  HUF("Hungarian forint", "Ft", "HUF", "Hungary"),
  JPY("Japanese yen", "¥", "JPY", "Japan", "Zimbabwe"),
  LAK("Lao kip", "₭", "LAK", "Laos"),
  FKP("Falkland Islands pound", "£", "FKP", "Falkland Islands"),
  IMP("Manx pound", "£", "IMP", "Isle of Man"),
  KZT("Kazakhstani tenge", "₸", "KZT", "Kazakhstan"),
  BAM("Bosnia and Herzegovina convertible mark", "KM or КМ", "BAM", "Bosnia and Herzegovina"),
  BDT("Bangladeshi taka", "৳", "BDT", "Bangladesh"),
  GMD("Gambian dalasi", "D", "GMD", "The Gambia"),
  NIO("Nicaraguan córdoba", "C$", "NIO", "Nicaragua"),
  NOK("Norwegian krone", "kr", "NOK", "Norway"),
  BGN("Bulgarian lev", "лв", "BGN", "Bulgaria"),
  PYG("Paraguayan guaraní", "₲", "PYG", "Paraguay"),
  GGP("Guernsey pound", "£", "GGP", "Alderney"),
  BBD("Barbadian dollar", "$", "BBD", "Barbados"),
  CLP("Chilean peso", "$", "CLP", "Chile"),
  CVE("Cape Verdean escudo", "Esc or $", "CVE", "Cape Verde"),
  EGP("Egyptian pound", "£ or ج.م", "EGP", "Egypt"),
  KRW("South Korean won", "₩", "KRW", "South Korea"),
  DZD("Algerian dinar", "د.ج", "DZD", "Algeria", "Sahrawi Republic"),
  BMD("Bermudian dollar", "$", "BMD", "Bermuda"),
  NGN("Nigerian naira", "₦", "NGN", "Nigeria"),
  TZS("Tanzanian shilling", "Sh", "TZS", "Tanzania"),
  UGX("Ugandan shilling", "Sh", "UGX", "Uganda"),
  UYU("Uruguayan peso", "$", "UYU", "Uruguay"),
  MYR("Malaysian ringgit", "RM", "MYR", "Malaysia"),
  FJD("Fijian dollar", "$", "FJD", "Fiji"),
  BHD("Bahraini dinar", ".د.ب", "BHD", "Bahrain"),
  XAF("Central African CFA franc", "Fr", "XAF", "Cameroon", "Central African Republic", "Chad", "Republic of the Congo", "Equatorial Guinea", "Gabon"),
  XCD("East Caribbean dollar", "$", "XCD", "Dominica", "Grenada", "Montserrat", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Anguilla", "Antigua and Barbuda"),
  GIP("Gibraltar pound", "£", "GIP", "Gibraltar"),
  NAD("Namibian dollar", "$", "NAD", "Namibia"),
  MDL("Moldovan leu", "L", "MDL", "Moldova"),
  MZN("Mozambican metical", "MT", "MZN", "Mozambique"),
  AZN("Azerbaijani manat", "₼", "AZN", "Azerbaijan"),
  HRK("Croatian kuna", "kn", "HRK", "Croatia"),
  MVR("Maldivian rufiyaa", ".ރ", "MVR", "Maldives"),
  STD("São Tomé and Príncipe dobra", "Db", "STD", "São Tomé and Príncipe"),
  CUP("Cuban peso", "$", "CUP", "Cuba"),
  DJF("Djiboutian franc", "Fr", "DJF", "Djibouti"),
  KPW("North Korean won", "₩", "KPW", "orth Korea"),
  ILS("Israeli new shekel", "₪", "ILS", "Israel", "Palestine"),
  PLN("Polish złoty", "zł", "PLN", "Poland"),
  INR("Indian rupee", "₹", "INR", "Bhutan", "India", "Zimbabwe"),
  GTQ("Guatemalan quetzal", "Q", "GTQ", "Guatemala"),
  IRR("Iranian rial", "﷼", "IRR", "Iran"),
  MNT("Mongolian tögrög", "₮", "MNT", "Mongolia"),
  GYD("Guyanese dollar", "$", "GYD", "Guyana"),
  JEP("Jersey pound", "£", "JEP", "Jersey"),
  OMR("Omani rial", "ر.ع.", "OMR", "Oman"),
  NZD("New Zealand dollar", "$", "NZD", "Cook Islands", "New Zealand", "Niue", "Pitcairn Islands"),
  ANG("Netherlands Antillean guilder", "ƒ", "ANG", "Curaçao", "Sint Maarten"),
  UZS("Uzbekistani soʻm", "₸", "UZS", "Uzbekistan"),
  KHR("Cambodian riel", "៛", "KHR", "Cambodia"),
  TOP("Tongan paʻanga", "T$", "TOP", "Tonga"),
  SOS("Somali shilling", "Sh", "SOS", "Somalia"),
  RUB("Russian ruble", "₽", "RUB", "Abkhazia", "Russia", "South Ossetia", "Ukraine"),
  BYN("Belarusian ruble", "Br", "BYN", "Belarus"),
  CAD("Canadian dollar", "$", "CAD", "Canada"),
  THB("Thai baht", "฿", "THB", "Thailand"),
  BIF("Burundian franc", "Fr", "BIF", "Burundi"),
  MAD("Moroccan dirham", "د. م.", "MAD", "Sahrawi Republic", "Morocco"),
  HTG("Haitian gourde", "G", "HTG", "Haiti"),
  MUR("Mauritian rupee", "₨", "MUR", "Mauritius"),
  PHP("Philippine peso", "₱", "PHP", "Philippines"),
  DKK("Danish krone", "kr", "DKK", "Denmark", "Faroe Islands"),
  HNL("Honduran lempira", "L", "HNL", "Honduras"),
  AMD("Armenian dram", "Armenian dram sign.svg", "AMD", "Armenia", "Republic of Artsakh"),
  AUD("Australian dollar", "$", "AUD", "Australia", "Cocos (Keeling) Islands", "Kiribati", "Nauru", "Tuvalu"),
  LKR("Sri Lankan rupee", "Rs or රු", "LKR", "Sri Lanka"),
  BRL("Brazilian real", "R$", "BRL", "Brazil"),
  KWD("Kuwaiti dinar", "د.ك", "KWD", "Kuwait"),
  RON("Romanian leu", "lei", "RON", "Romania"),
  SGD("Singapore dollar", "$", "SGD", "Brunei", "Singapore"),
  IQD("Iraqi dinar", "ع.د", "IQD", "Iraq"),
  CDF("Congolese franc", "Fr", "CDF", "Democratic Republic of the Congo"),
  HKD("Hong Kong dollar", "$", "HKD", "Hong Kong"),
  AED("United Arab Emirates dirham", "د.إ", "AED", "United Arab Emirates"),
  USD("United States dollar", "$", "USD", "Bonaire", "British Indian Ocean Territory", "British Virgin Islands", "Cambodia", "East Timor", "Ecuador", "El Salvador", "Marshall Islands", "Micronesia", "Palau", "Panama", "Saba", "Sint Eustatius", "Turks and Caicos Islands", "United States"),
  BZD("Belize dollar", "$", "BZD", "Belize"),
  GEL("Georgian lari", "₾", "GEL", "Georgia"),
  SRD("Surinamese dollar", "$", "SRD", "Suriname"),
  LYD("Libyan dinar", "ل.د", "LYD", "Libya"),
  MRO("Mauritanian ouguiya", "UM", "MRO", "Mauritania", "Sahrawi Republic"),
  MXN("Mexican peso", "$", "MXN", "Mexico"),
  PGK("Papua New Guinean kina", "K", "PGK", "Papua New Guinea"),
  SEK("Swedish krona", "kr", "SEK", "Sweden"),
  WST("Samoan tālā", "T", "WST", "Samoa"),
  YER("Yemeni rial", "﷼", "YER", "Yemen"),
  SHP("Saint Helena pound", "£", "SHP", "nited Kingdom Ascension Island", "Saint Helena", "Tristan da Cunha"),
  IDR("Indonesian rupiah", "Rp", "IDR", "Indonesia"),
  CUC("Cuban convertible peso", "$", "CUC", "Cuba"),
  MOP("Macanese pataca", "P", "MOP", "Macau"),
  TND("Tunisian dinar", "د.ت", "TND", "Tunisia"),
  GHS("Ghanaian cedi", "₵", "GHS", "Ghana"),
  MGA("Malagasy ariary", "Ar", "MGA", "Madagascar"),
  MKD("Macedonian denar", "ден", "MKD", "Republic of Macedonia"),
  VND("Vietnamese đồng", "₫", "VND", "Vietnam"),
  TRY("Turkish lira", "₺", "TRY", "Northern Cyprus", "Turkey"),
  MWK("Malawian kwacha", "MK", "MWK", "Malawi"),
  TTD("Trinidad and Tobago dollar", "$", "TTD", "Trinidad and Tobago"),
  TVD("Tuvaluan dollar", "$", "TVD", "Tuvalu"),
  SYP("Syrian pound", "£ or ل.س", "SYP", "Syria"),
  ARS("Argentine peso", "$", "ARS", "Argentina"),
  BWP("Botswana pula", "P", "BWP", "Botswana", "Zimbabwe"),
  LBP("Lebanese pound", "ل.ل", "LBP", "Lebanon"),
  SBD("Solomon Islands dollar", "$", "SBD", "Solomon Islands"),
  XOF("West African CFA franc", "Fr", "XOF", "Benin", "Burkina Faso", "Côte d'Ivoire", "Guinea-Bissau", "Mali", "Niger", "Senegal", "Togo"),
  TMT("Turkmenistan manat", "m", "TMT", "Turkmenistan"),
  ALL("Albanian lek", "L", "ALL", "Albania"),
  MMK("Burmese kyat", "Ks", "MMK", "Myanmar"),
  KMF("Comorian franc", "Fr", "KMF", "Comoros"),
  CHF("Swiss franc", "Fr", "CHF", "Liechtenstein", " Switzerland"),
  BND("Brunei dollar", "$", "BND", "Brunei", "Singapore"),
  ETB("Ethiopian birr", "Br", "ETB", "Ethiopia"),
  ISK("Icelandic króna", "kr", "ISK", "Iceland"),
  SAR("Saudi riyal", "ر.س", "SAR", "Saudi Arabia"),
  TWD("New Taiwan dollar", "$", "TWD", "Taiwan"),
  CNY("Chinese yuan", "¥ or 元", "CNY", "China", "Zimbabwe"),
  LSL("Lesotho loti", "L", "LSL", "Lesotho"),
  PEN("Peruvian sol", "S/.", "PEN", "Peru"),
  BSD("Bahamian dollar", "$", "BSD", "The Bahamas"),
  TJS("Tajikistani somoni", "ЅМ", "TJS", "Tajikistan"),
  RWF("Rwandan franc", "Fr", "RWF", "Rwanda"),
  ZMW("Zambian kwacha", "ZK", "ZMW", "Zambia"),
  GBP("British pound", "£", "GBP", "Alderney", "Guernsey", "Isle of Man", "Jersey", "South Georgia and the South Sandwich Islands", "United Kingdom", "Zimbabwe"),
  CZK("Czech koruna", "Kč", "CZK", "Czech Republic"),
  SCR("Seychellois rupee", "₨", "SCR", "Seychelles");

  public final String[] countries;
  public final String currencyName;
  public final String symbol;
  public final String code;

  //s[0] = currency name, s[1] = symbol, s[2] = code, anything that follows is country
  private Currency(String... s){
    this.currencyName = s[0];
    this.symbol = s[1];
    this.code = s[2];
    List<String> countries = new ArrayList<>();
    countries.addAll(Arrays.asList(s).subList(3, s.length));
    this.countries = (String[]) countries.toArray();
  }

}
